CREATE TABLE Sber (
    BUSINESS_DT DATE NOT NULL,
    ACCOUNT_DEBIT_ID INT NOT NULL,
    ACCOUNT_CREDIT_ID INT NOT NULL,
    POSTING_AMT INT NOT NULL
);

INSERT INTO Sber (BUSINESS_DT, ACCOUNT_DEBIT_ID, ACCOUNT_CREDIT_ID, POSTING_AMT)
VALUES (TO_DATE('01.01.20','DD.MM.YY'), 1, 2, 1000);
INSERT INTO Sber (BUSINESS_DT, ACCOUNT_DEBIT_ID, ACCOUNT_CREDIT_ID, POSTING_AMT)
VALUES (TO_DATE('05.01.20','DD.MM.YY'), 2, 1, 500);
INSERT INTO Sber (BUSINESS_DT, ACCOUNT_DEBIT_ID, ACCOUNT_CREDIT_ID, POSTING_AMT)
VALUES (TO_DATE('04.02.20','DD.MM.YY'), 2, 1, 500);
INSERT INTO Sber (BUSINESS_DT, ACCOUNT_DEBIT_ID, ACCOUNT_CREDIT_ID, POSTING_AMT)
VALUES (TO_DATE('04.03.20','DD.MM.YY'), 1, 2, 1000);
INSERT INTO Sber (BUSINESS_DT, ACCOUNT_DEBIT_ID, ACCOUNT_CREDIT_ID, POSTING_AMT)
VALUES (TO_DATE('05.04.20','DD.MM.YY'), 2, 1, 500);
INSERT INTO Sber (BUSINESS_DT, ACCOUNT_DEBIT_ID, ACCOUNT_CREDIT_ID, POSTING_AMT)
VALUES (TO_DATE('06.04.20','DD.MM.YY'), 1, 2, 100);
INSERT INTO Sber (BUSINESS_DT, ACCOUNT_DEBIT_ID, ACCOUNT_CREDIT_ID, POSTING_AMT)
VALUES (TO_DATE('07.04.20','DD.MM.YY'), 1, 2, 230);
INSERT INTO Sber (BUSINESS_DT, ACCOUNT_DEBIT_ID, ACCOUNT_CREDIT_ID, POSTING_AMT)
VALUES (TO_DATE('08.04.20','DD.MM.YY'), 2, 1, 600);